---
title: "Assignment 6"
format: docx
editor: visual
---

### Load the Dataset

```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(dplyr)
plots <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-02/plots.csv')
species <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-02/species.csv')
surveys <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-02/surveys.csv')
```

#### Preliminary calculations and graphs

```{r}
#overview of datasets
summary(surveys)
```

```{r}
#total number of individuals observed for each species each year
surveysTotal <- surveys %>% 
  group_by(species, year) %>% 
  summarize(total = sum(n()))

#lineplot of total number of individuals observed over the years
ggplot(surveysTotal, aes(x = year, y = total, color = species)) +
  geom_line() +
  scale_x_continuous(limits = c(1970, 2022), breaks = seq(1970, 2020, by = 10)) +
  labs(x = "Year", y = "Total number of individuals", color = "Species ID")
```

```{r}
# Left join the species data to the surveys data by species
surveys_species <- surveys %>%
  left_join(species, by = "species")


#annual rate of change in abundance for each species
rateOfchange <- surveys_species %>%
  group_by(species, year) %>%
  summarize(total = sum(hfl, na.rm = TRUE)) %>%
  arrange(species, year) %>%
  mutate(change = total - lag(total), rate = change / lag(total))

# Remove the first year of data for each species since we don't have a previous year to compare to
rateOfchange <- rateOfchange %>%
  filter(!is.na(rate))

#bar chart of the annual rate of change in abundance for each species
ggplot(rateOfchange, aes(x = species, y = rate, fill = rate < 0)) +
  geom_col() +
  labs(x = "Species ID", y = "Annual rate of change in abundance") +
  scale_fill_manual(values = c("green4", "red"), guide = FALSE) +
  coord_flip()
```

```{r}
#The number of unique species observed in each year
species_counts <- surveys %>%
  group_by(year) %>%
  summarise(numberSpecies = n_distinct(species))

#Line plot of species counts over time
ggplot(species_counts, aes(x = year, y = numberSpecies)) +
  geom_line() +
  xlab("Year") +
  ylab("Number of Species Observed") +
  ggtitle("Trend in Species Diversity Over Time") +
  theme_minimal()
```

### Story

The changes in the number of different species observed between years were more gradual during the early years of the study, but in the later years, the changes became more pronounced and varied widely.

### Graph

```{r}
# Define the boundaries of the shaded region
early_years <- c(1978, 1993)
late_years <- c(2004, 2020)

ggplot(species_counts, aes(x = year, y = numberSpecies)) +
  geom_line() +
  geom_rect(xmin = early_years[1], xmax = early_years[2], ymin = -Inf, ymax = Inf, fill = "#A9CCE3", alpha = 0.01) +
  geom_rect(xmin = late_years[1], xmax = late_years[2], ymin = -Inf, ymax = Inf, fill = "#A9CCE3", alpha = 0.01) +
  scale_y_continuous(limits = c(5, 16.5), breaks = seq(0, 18, by = 2)) +
  labs(x = "Year", y = "Number of Different Species Observed", title = "Trend in Species Diversity Over Time") +
  scale_x_continuous(breaks = seq(1980, 2022, by = 5)) +
  geom_text(aes(label = "Less dramatic changes in\nnumber of species observed", x = 1983, y = 5.5, hjust = 0.3, vjust = 0.5), size = 2.5) +
  geom_text(aes(label = "More significant changes in\nnumber of species observed", x = 2009, y = 5.5, hjust = 0.3, vjust = 0.5), size = 2.5) + 
  theme_minimal() +
  theme(text = element_text(size = 12), panel.grid.minor = element_blank())
```
