---
title: "Dashboard: Baseball Stats"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(scales)
library(ggforce)
library(shiny)
library(ggiraph)
library(plotly)
Nestor <- read.csv('combined_data.csv')
Nestor <- Nestor %>%
  select(Pitcher, SpinRate, SpinAxis, RelSpeed, ExitSpeed, PitchCall, TaggedPitchType)%>%
  filter(Pitcher== 'German, Nestor')
N1 <- Nestor%>%
  select(TaggedPitchType, PitchCall)%>%
  mutate(CountsAsStrike = ifelse(PitchCall %in% c('FoulBall','StrikeCalled','StrikeSwinging'),'Strike','Not a Strike')) %>%
  group_by(TaggedPitchType, CountsAsStrike)%>%
  summarise(num_by_pitch_call = n(), .groups = 'drop') %>%
  group_by(TaggedPitchType) %>%
  mutate(num_by_pitch = sum(num_by_pitch_call)) %>%
  mutate(ShareofPitchCall = num_by_pitch_call/num_by_pitch)
```

Row {data-height=525}
-----------------------------------------------------------------------

### Spin Rate vs Release Speed by Pitch Type
```{r}
p1 <- ggplot(Nestor, aes(y = RelSpeed, x = SpinRate, color = TaggedPitchType))+ 
  geom_point_interactive(aes(y = RelSpeed, x = SpinRate, color = TaggedPitchType, tooltip = paste(TaggedPitchType, "\nRelease speed: ", RelSpeed,"mph", "\nSpin Rate: ", SpinRate, "rpm"))) +
  labs(y = "Release Speed (mph)", x = "Spin Rate (rpm)", color = "Pitch Type") +
  theme_minimal() +
  theme(panel.grid.minor.y = element_blank(),
        axis.text = element_text(family = 'serif', size = 11),
        axis.title = element_text(family = 'serif', size = 11),
        legend.text = element_text(family = 'serif', size = 8),
        legend.title = element_text(family = 'serif', size = 8)) 

ggiraph(ggobj = p1, height_svg = 2.80)
```

### Exit Velocity vs Pitch Speed by Pitch Type
```{r fig.height = 3, echo=FALSE, message=FALSE, warning=FALSE}
p2 <- ggplot(Nestor, aes(y = RelSpeed, x = ExitSpeed, color = TaggedPitchType))+
  geom_point_interactive(aes(y = RelSpeed, x = ExitSpeed, color = TaggedPitchType, tooltip = paste(TaggedPitchType,"\nRelease speed: ", RelSpeed, "mph", "\nExit Velocity: ", ExitSpeed, "mph"))) +
  labs(y= "Release Speed (mph)", x = "Exit Velocity (mph)", color = "Pitch Type") +
  scale_y_continuous(breaks= seq(0, 110, by = 10)) +
  facet_zoom(xlim = c(50,110)) +
  theme(panel.grid.minor.x = element_blank(),
        axis.text = element_text(family = 'serif', size = 15),
        axis.title = element_text(family = 'serif', size = 15), 
        legend.text = element_text(family = 'serif', size = 8)) 

ggiraph(ggobj = p2, width_svg = 8, height_svg = 3.75)
```


Row {data-height=475}
-----------------------------------------------------------------------

### Share of Pitch Calls vs Pitch Type
```{r fig.width = 10, fig.height = 4,echo=FALSE, message=FALSE, warning=FALSE, results='hide'}

ggplot(N1, aes(x = TaggedPitchType, y = ShareofPitchCall, fill = CountsAsStrike)) +
  geom_col() +
  labs(x = "Pitch Type", y = "Share of Pitch Call") +
  geom_text(position = "fill", vjust = 1.5, aes(label = percent(ShareofPitchCall, accuracy = 0.01), size = 20)) +
  guides(fill = guide_legend(title = NULL), size = 'none') +
  scale_fill_manual(values = c("Not a Strike" = "grey67", "Strike" = "red3")) +
  scale_y_continuous(labels = percent) +
  theme_minimal() +
  theme(panel.grid.minor.y = element_blank(),
        axis.text = element_text(family = 'serif', size = 16),
        axis.title = element_text(family = 'serif', size = 18),
        legend.text = element_text(family = 'serif', size = 14)) 

```

### Swing and Miss Percentage by Pitch Type

```{r fig.width = 10, fig.height= 4}
N2 <- Nestor%>%
  select(PitchCall, TaggedPitchType)%>%
  group_by(TaggedPitchType)%>%
  summarise(WiffPercentage = mean(PitchCall == 'StrikeSwinging'))

ggplot(N2, aes(x = reorder(TaggedPitchType, -WiffPercentage), y = WiffPercentage))+ 
  geom_col(fill = "grey34") +
  labs(x = "Pitch Type", y = "Wiff Percentage") +
  scale_y_continuous(label = percent, limits = c(0,0.20)) +
  geom_text(aes(label = percent(WiffPercentage, accuracy = 0.01), size = 15), vjust = -0.5) +
  theme_minimal() + 
  guides(size = 'none') +
  theme(panel.grid.minor.y = element_blank(),
        axis.text = element_text(family = 'serif', size = 16),
        axis.title = element_text(family = 'serif', size = 18),
        legend.text = element_text(family = 'serif', size = 14)) 
```
